{"uuid": "8a6b95e6-fba1-4d33-942d-d1e5b0031671", "counter": 12, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.NoCredentialsError: Unable to locate credentials\u001b[0m\r\n\u001b[0;31mfatal: [localhost]: FAILED! => {\"boto3_version\": \"1.22.5\", \"botocore_version\": \"1.25.5\", \"changed\": false, \"msg\": \"error describing images: Unable to locate credentials\"}\u001b[0m", "start_line": 11, "end_line": 13, "runner_ident": "77680e8c-6544-4836-add5-54e4418ec646", "event": "runner_on_failed", "pid": 20, "created": "2022-05-03T16:15:53.591047", "parent_uuid": "52bbce5b-c4f9-0a65-e77f-000000000007", "event_data": {"playbook": "amazon_ami.yaml", "playbook_uuid": "e962dfe1-24d0-4068-b6b6-b43992f3a761", "play": "localhost", "play_uuid": "52bbce5b-c4f9-0a65-e77f-000000000005", "play_pattern": "localhost", "task": "test fake playbook against EE", "task_uuid": "52bbce5b-c4f9-0a65-e77f-000000000007", "task_action": "amazon.aws.ec2_ami_info", "task_args": "", "task_path": "/runner/project/amazon_ami.yaml:4", "host": "localhost", "remote_addr": "127.0.0.1", "res": {"exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_amazon.aws.ec2_ami_info_payload_yth27s73/ansible_amazon.aws.ec2_ami_info_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_ami_info.py\", line 243, in list_ec2_images\n  File \"/tmp/ansible_amazon.aws.ec2_ami_info_payload_yth27s73/ansible_amazon.aws.ec2_ami_info_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/core.py\", line 336, in deciding_wrapper\n    return retrying_wrapper(*args, **kwargs)\n  File \"/tmp/ansible_amazon.aws.ec2_ami_info_payload_yth27s73/ansible_amazon.aws.ec2_ami_info_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 118, in _retry_wrapper\n    return _retry_func(\n  File \"/tmp/ansible_amazon.aws.ec2_ami_info_payload_yth27s73/ansible_amazon.aws.ec2_ami_info_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 68, in _retry_func\n    return func()\n  File \"/usr/local/lib/python3.8/site-packages/botocore/client.py\", line 415, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/client.py\", line 731, in _make_api_call\n    http, parsed_response = self._make_request(\n  File \"/usr/local/lib/python3.8/site-packages/botocore/client.py\", line 751, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/endpoint.py\", line 107, in make_request\n    return self._send_request(request_dict, operation_model)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/endpoint.py\", line 180, in _send_request\n    request = self.create_request(request_dict, operation_model)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/endpoint.py\", line 120, in create_request\n    self._event_emitter.emit(event_name, request=request,\n  File \"/usr/local/lib/python3.8/site-packages/botocore/hooks.py\", line 358, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/hooks.py\", line 229, in emit\n    return self._emit(event_name, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/hooks.py\", line 212, in _emit\n    response = handler(**kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/signers.py\", line 95, in handler\n    return self.sign(operation_name, request)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/signers.py\", line 167, in sign\n    auth.add_auth(request)\n  File \"/usr/local/lib/python3.8/site-packages/botocore/auth.py\", line 401, in add_auth\n    raise NoCredentialsError()\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\n", "boto3_version": "1.22.5", "botocore_version": "1.25.5", "msg": "error describing images: Unable to locate credentials", "invocation": {"module_args": {"image_ids": ["ami_fake"], "region": "us-east-1", "debug_botocore_endpoint_logs": false, "validate_certs": true, "filters": {}, "owners": [], "executable_users": [], "describe_image_attributes": false, "ec2_url": null, "aws_access_key": null, "aws_secret_key": null, "security_token": null, "aws_ca_bundle": null, "profile": null, "aws_config": null}}, "_ansible_no_log": false, "changed": false}, "start": "2022-05-03T16:15:50.808800", "end": "2022-05-03T16:15:53.590906", "duration": 2.782106, "ignore_errors": null, "event_loop": null, "uuid": "8a6b95e6-fba1-4d33-942d-d1e5b0031671"}}